spring:
  application:
    name: hystrix

server:
  port: 9001

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

feign:
  hystrix:
    enabled: true
# 配置Hystrix Metrics Stream
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
